
import { Artwork, Book, Category, JournalPost, Language } from './types';

// Security Key for Admin Panel
export const ADMIN_SECRET_KEY = 'Dr.Archetype_Secure_Gateway_#99_Philosophy_&_Art_!!';

// Helper to get localized content
export const getLocalized = (item: any, field: string, lang: Language) => {
  if (lang === 'en') return item[field];
  const val = item[`${field}_${lang}`];
  return val || item[field]; // Fallback to English
};

export const UI_TEXT = {
  nav_works: { en: 'Works', fa: 'آثار', fr: 'Œuvres', de: 'Werke', ru: 'Работы', tr: 'Eserler', ar: 'الأعمال', zh: '作品' },
  nav_books: { en: 'Books', fa: 'کتاب‌ها', fr: 'Livres', de: 'Bücher', ru: 'Книги', tr: 'Kitaplar', ar: 'الكتب', zh: '书籍' },
  nav_journal: { en: 'Journal', fa: 'جستارها', fr: 'Journal', de: 'Journal', ru: 'Журнал', tr: 'Dergi', ar: 'المجلة', zh: '日志' },
  nav_bio: { en: 'Biography', fa: 'بیوگرافی', fr: 'Biographie', de: 'Biografie', ru: 'Биография', tr: 'Biyografi', ar: 'السيرة الذاتية', zh: '传记' },
  nav_admin: { en: 'Command Center', fa: 'پنل مدیریت', fr: 'Centre de Commande', de: 'Kommandozentrale', ru: 'Центр Управления', tr: 'Komuta Merkezi', ar: 'مركز القيادة', zh: '指挥中心' },
  
  hero_subtitle: { en: 'PHILOSOPHY & ART', fa: 'فلسفه و هنر', fr: 'PHILOSOPHIE & ART', de: 'PHILOSOPHIE & KUNST', ru: 'ФИЛОСОФИЯ И ИСКУССТВО', tr: 'FELSEFE VE SANAT', ar: 'الفلسفة والفن', zh: '哲学与艺术' },
  hero_title_prefix: { en: 'The Logic of', fa: 'منطقِ', fr: 'La Logique de', de: 'Die Logik der', ru: 'Логика', tr: 'Mantığı', ar: 'منطق', zh: '逻辑之' },
  hero_title_highlight: { en: 'Beauty', fa: 'زیبایـی', fr: 'la Beauté', de: 'Schönheit', ru: 'Красоты', tr: 'Güzellik', ar: 'الجمال', zh: '美' },
  hero_desc: { 
    en: 'Bridging the gap between western metaphysics and visual communication.',
    fa: 'پلی میان متافیزیک غرب و ارتباطات بصری.',
    fr: 'Combler le fossé entre la métaphysique occidentale et la communication visuelle.',
    de: 'Die Lücke zwischen westlicher Metaphysik und visueller Kommunikation schließen.',
    ru: 'Мост между западной метафизикой и визуальной коммуникацией.',
    tr: 'Batı metafiziği ile görsel iletişim arasındaki boşluğu doldurmak.',
    ar: 'سد الفجوة بين الميتافيزيقيا الغربية والاتصال البصري.',
    zh: '弥合西方形而上学与视觉传达之间的鸿沟。'
  },
  
  btn_view_works: { en: 'View Works', fa: 'مشاهده آثار', fr: 'Voir les Œuvres', de: 'Werke ansehen', ru: 'Смотреть работы', tr: 'Eserleri Gör', ar: 'عرض الأعمال', zh: '查看作品' },
  btn_published_books: { en: 'Published Books', fa: 'کتاب‌های منتشر شده', fr: 'Livres Publiés', de: 'Veröffentlichte Bücher', ru: 'Опубликованные книги', tr: 'Yayınlanan Kitaplar', ar: 'الكتب المنشورة', zh: '出版书籍' },
  
  quote: {
    en: 'Art is not merely an imitation of the reality, but the sensory manifestation of the Idea itself.',
    fa: 'هنر صرفاً تقلید از واقعیت نیست، بلکه تجلی حسیِ خودِ ایده است.',
    fr: "L'art n'est pas simplement une imitation de la réalité, mais la manifestation sensorielle de l'Idée elle-même.",
    de: 'Kunst ist nicht bloß eine Nachahmung der Realität, sondern die sinnliche Manifestation der Idee selbst.',
    ru: 'Искусство — это не просто подражание реальности, а чувственное проявление самой Идеи.',
    tr: 'Sanat sadece gerçekliğin taklidi değil, İdea’nın kendisinin duyusal tezahürüdür.',
    ar: 'الفن ليس مجرد تقليد للواقع، بل هو التجلي الحسي للفكرة ذاتها.',
    zh: '艺术不仅仅是对现实的模仿，而是理念本身的感官体现。'
  },
  thesis_ref: { en: 'DOCTORAL THESIS, 2018', fa: 'رساله دکتری، ۲۰۱۸', fr: 'THÈSE DE DOCTORAT, 2018', de: 'DOKTORARBEIT, 2018', ru: 'ДОКТОРСКАЯ ДИССЕРТАЦИЯ, 2018', tr: 'DOKTORA TEZİ, 2018', ar: 'أطروحة الدكتوراه، ٢٠١٨', zh: '博士论文，2018' },
  
  portfolio_title: { en: 'Selected Works', fa: 'آثار برگزیده', fr: 'Œuvres Choisies', de: 'Ausgewählte Werke', ru: 'Избранные Работы', tr: 'Seçilmiş Eserler', ar: 'أعمال مختارة', zh: '精选作品' },
  portfolio_subtitle: { 
    en: 'A curated collection spanning 15 years.', 
    fa: 'مجموعه‌ای گزینش‌شده از ۱۵ سال فعالیت.', 
    fr: 'Une collection organisée couvrant 15 ans.', 
    de: 'Eine kuratierte Sammlung aus 15 Jahren.', 
    ru: 'Курируемая коллекция за 15 лет.', 
    tr: '15 yılı kapsayan küratörlü bir koleksiyon.',
    ar: 'مجموعة منسقة تغطي ١٥ عاماً.',
    zh: '跨越15年的精选集。'
  },
  
  full_details: { en: 'Full Details', fa: 'جزئیات کامل', fr: 'Détails Complets', de: 'Alle Details', ru: 'Полные детали', tr: 'Tam Detaylar', ar: 'التفاصيل الكاملة', zh: '完整详情' },
  
  books_library: { en: 'The Library', fa: 'کتابخانه', fr: 'La Bibliothèque', de: 'Die Bibliothek', ru: 'Библиотека', tr: 'Kütüphane', ar: 'المكتبة', zh: '图书馆' },
  add_to_cart: { en: 'Add to Cart', fa: 'افزودن به سبد', fr: 'Ajouter au Panier', de: 'In den Warenkorb', ru: 'В корзину', tr: 'Sepete Ekle', ar: 'أضف إلى السلة', zh: '加入购物车' },
  
  journal_title: { en: 'Philosophical Journal', fa: 'جستارهای فلسفی', fr: 'Journal Philosophique', de: 'Philosophisches Journal', ru: 'Философский Журнал', tr: 'Felsefi Dergi', ar: 'المجلة الفلسفية', zh: '哲学期刊' },
  read_essay: { en: 'Read Essay', fa: 'مطالعه مقاله', fr: 'Lire l\'Essai', de: 'Essay lesen', ru: 'Читать эссе', tr: 'Makaleyi Oku', ar: 'قراءة المقال', zh: '阅读文章' },

  cart_title: { en: 'Your Collection', fa: 'سبد خرید', fr: 'Votre Collection', de: 'Ihre Sammlung', ru: 'Ваша Коллекция', tr: 'Koleksiyonunuz', ar: 'مجموعتك', zh: '您的收藏' },
  cart_empty: { en: 'Your cart is empty', fa: 'سبد خرید خالی است', fr: 'Votre panier est vide', de: 'Ihr Warenkorb ist leer', ru: 'Ваша корзина пуста', tr: 'Sepetiniz boş', ar: 'سلة التسوق فارغة', zh: '您的购物车是空的' },
  checkout: { en: 'Checkout', fa: 'تکمیل خرید', fr: 'Paiement', de: 'Kasse', ru: 'Оформить', tr: 'Ödeme', ar: 'الدفع', zh: '结账' },
  
  about_artist: { en: 'The Artist', fa: 'درباره هنرمند', fr: 'L\'Artiste', de: 'Der Künstler', ru: 'Художник', tr: 'Sanatçı Hakkında', ar: 'الفنان', zh: '艺术家' },
  education: { en: 'Education', fa: 'تحصیلات', fr: 'Éducation', de: 'Ausbildung', ru: 'Образование', tr: 'Eğitim', ar: 'التعليم', zh: '教育背景' },
  contact: { en: 'Contact', fa: 'تماس', fr: 'Contact', de: 'Kontakt', ru: 'Контакт', tr: 'İletişim', ar: 'اتصال', zh: '联系' },
  awards: { en: 'Awards', fa: 'جوایز', fr: 'Prix', de: 'Auszeichnungen', ru: 'Награды', tr: 'Ödüller', ar: 'الجوائز', zh: '奖项' },
  
  quick_links: { en: 'Quick Links', fa: 'دسترسی سریع', fr: 'Liens Rapides', de: 'Schnelllinks', ru: 'Быстрые ссылки', tr: 'Hızlı Linkler', ar: 'روابط سريعة', zh: '快速链接' },
  designed_with: { en: 'Designed with Philosophy', fa: 'طراحی شده با فلسفه', fr: 'Conçu avec Philosophie', de: 'Mit Philosophie entworfen', ru: 'Разработано с философией', tr: 'Felsefe ile tasarlandı', ar: 'صمم بفلسفة', zh: '以哲学设计' },
};

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'The Dialectic of Silence',
    title_fa: 'دیالکتیک سکوت',
    title_fr: 'La Dialectique du Silence',
    title_de: 'Die Dialektik der Stille',
    title_ru: 'Диалектика Тишины',
    title_tr: 'Sessizliğin Diyalektiği',
    title_ar: 'جدلية الصمت',
    title_zh: '沉默的辩证法',
    description: 'An exploration of the void between thought and expression.',
    description_fa: 'کاوشی در خلأ میان اندیشه و بیان.',
    description_fr: 'Une exploration du vide entre la pensée et l\'expression.',
    description_de: 'Eine Erkundung der Leere zwischen Gedanke und Ausdruck.',
    description_ru: 'Исследование пустоты между мыслью и выражением.',
    description_tr: 'Düşünce ve ifade arasındaki boşluğun keşfi.',
    description_ar: 'استكشاف للفراغ بين الفكر والتعبير.',
    description_zh: '探索思想与表达之间的虚空。',
    year: 2023,
    category: Category.PAINTING,
    imageUrl: 'https://picsum.photos/800/600?grayscale',
    featured: true,
    dimensions: '120x150 cm',
    technique: 'Oil on Canvas',
    technique_fa: 'رنگ روغن روی بوم',
    technique_fr: 'Huile sur toile',
    technique_de: 'Öl auf Leinwand',
    technique_ru: 'Масло, холст',
    technique_tr: 'Tuval üzerine yağlı boya',
    technique_ar: 'زيت على قماش',
    technique_zh: '布面油画'
  },
  {
    id: '2',
    title: 'Ontological Red',
    title_fa: 'قرمز هستی‌شناسانه',
    title_fr: 'Rouge Ontologique',
    title_de: 'Ontologisches Rot',
    title_ru: 'Онтологический Красный',
    title_tr: 'Ontolojik Kırmızı',
    title_ar: 'الأحمر الوجودي',
    title_zh: '本体论之红',
    description: 'A visual representation of Being qua Being through crimson.',
    description_fa: 'بازنمایی بصریِ «هستی بما هو هستی» از طریق رنگ لاکی.',
    description_fr: 'Une représentation visuelle de l\'Être en tant qu\'Être.',
    description_de: 'Eine visuelle Darstellung des Seins als Sein.',
    description_ru: 'Визуальное представление Бытия как Бытия.',
    description_tr: 'Varlığın Varlık olarak görsel temsili.',
    description_ar: 'تمثيل بصري للوجود بما هو وجود من خلال اللون القرمزي.',
    description_zh: '通过深红色对“存在之为存在”的视觉呈现。',
    year: 2022,
    category: Category.GRAPHIC_DESIGN,
    imageUrl: 'https://picsum.photos/800/800?blur=2',
    featured: true,
    dimensions: 'Digital Print',
    technique: 'Vector & Raster',
    technique_fa: 'وکتور و رستر',
    technique_fr: 'Vecteur et Raster',
    technique_de: 'Vektor & Raster',
    technique_ru: 'Вектор и Растр',
    technique_tr: 'Vektör ve Raster',
    technique_ar: 'فيكتور وراستر',
    technique_zh: '矢量与光栅'
  },
  {
    id: '3',
    title: 'Structure of Time',
    title_fa: 'ساختار زمان',
    title_fr: 'Structure du Temps',
    title_de: 'Struktur der Zeit',
    title_ru: 'Структура Времени',
    title_tr: 'Zamanın Yapısı',
    title_ar: 'هيكل الزمن',
    title_zh: '时间的结构',
    description: 'Sculptural digital render challenging temporal linearity.',
    description_fa: 'رندر دیجیتال که خطی بودن زمان را به چالش می‌کشد.',
    description_fr: 'Rendu numérique sculptural défiant la linéarité temporelle.',
    description_de: 'Skulpturales digitales Rendering, das die Zeitlinearität herausfordert.',
    description_ru: 'Скульптурный цифровой рендер, бросающий вызов линейности времени.',
    description_tr: 'Zamanın doğrusallığına meydan okuyan heykelsi dijital render.',
    description_ar: 'تصيير رقمي نحتي يتحدى خطية الزمن.',
    description_zh: '挑战时间线性性的雕塑感数字渲染。',
    year: 2024,
    category: Category.DIGITAL,
    imageUrl: 'https://picsum.photos/600/900',
    featured: false,
    dimensions: 'Variable',
    technique: '3D Rendering',
    technique_fa: 'رندر سه بعدی',
    technique_fr: 'Rendu 3D',
    technique_de: '3D-Rendering',
    technique_ru: '3D-рендеринг',
    technique_tr: '3D Render',
    technique_ar: 'تصيير ثلاثي الأبعاد',
    technique_zh: '3D渲染'
  },
  {
    id: '4',
    title: 'Ethics of Form',
    title_fa: 'اخلاقِ فُرم',
    title_fr: 'Éthique de la Forme',
    title_de: 'Ethik der Form',
    title_ru: 'Этика Формы',
    title_tr: 'Biçim Etiği',
    title_ar: 'أخلاقيات الشكل',
    title_zh: '形式伦理',
    description: 'Minimalist photography of brutalist architecture.',
    description_fa: 'عکاسی مینیمالیستی از معماری بروتالیست.',
    description_fr: 'Photographie minimaliste de l\'architecture brutaliste.',
    description_de: 'Minimalistische Fotografie brutalistischer Architektur.',
    description_ru: 'Минималистичная фотография бруталистской архитектуры.',
    description_tr: 'Brütalist mimarinin minimalist fotoğrafçılığı.',
    description_ar: 'تصوير تبسيطي للعمارة الوحشية.',
    description_zh: '粗野主义建筑的极简摄影。',
    year: 2021,
    category: Category.PHOTOGRAPHY,
    imageUrl: 'https://picsum.photos/900/600',
    featured: false,
    dimensions: '50x70 cm',
    technique: 'Analog Photography',
    technique_fa: 'عکاسی آنالوگ',
    technique_fr: 'Photographie Analogique',
    technique_de: 'Analoge Fotografie',
    technique_ru: 'Аналоговая фотография',
    technique_tr: 'Analog Fotoğrafçılık',
    technique_ar: 'تصوير تناظري',
    technique_zh: '胶片摄影'
  }
];

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Aesthetics of Truth',
    title_fa: 'زیبایی‌شناسی حقیقت',
    title_fr: 'L\'Esthétique de la Vérité',
    title_de: 'Die Ästhetik der Wahrheit',
    title_ru: 'Эстетика Истины',
    title_tr: 'Hakikatin Estetiği',
    title_ar: 'جماليات الحقيقة',
    title_zh: '真理美学',
    subtitle: 'Reimagining Classical Beauty',
    subtitle_fa: 'بازخوانی زیبایی کلاسیک',
    subtitle_fr: 'Réimaginer la Beauté Classique',
    subtitle_de: 'Klassische Schönheit neu gedacht',
    subtitle_ru: 'Переосмысление классической красоты',
    subtitle_tr: 'Klasik Güzelliğin Yeniden Tasavvuru',
    subtitle_ar: 'إعادة تصور الجمال الكلاسيكي',
    subtitle_zh: '重构古典美',
    description: 'A study on how truth manifests in digital art.',
    description_fa: 'مطالعه‌ای در باب تجلی حقیقت در هنر دیجیتال.',
    description_fr: 'Une étude sur la manifestation de la vérité dans l\'art numérique.',
    description_de: 'Eine Studie darüber, wie sich Wahrheit in der digitalen Kunst manifestiert.',
    description_ru: 'Исследование того, как истина проявляется в цифровом искусстве.',
    description_tr: 'Dijital sanatta hakikatin nasıl tezahür ettiğine dair bir çalışma.',
    description_ar: 'دراسة حول كيفية تجلي الحقيقة في الفن الرقمي.',
    description_zh: '关于真理如何在数字艺术中显现的研究。',
    price: 45.00,
    coverUrl: 'https://picsum.photos/400/600?random=1',
    pages: 320,
    publishDate: '2022-11-15',
  },
  {
    id: '2',
    title: 'Shadows of Logic',
    title_fa: 'سایه‌های منطق',
    title_fr: 'Ombres de la Logique',
    title_de: 'Schatten der Logik',
    title_ru: 'Тени Логики',
    title_tr: 'Mantığın Gölgeleri',
    title_ar: 'ظلال المنطق',
    title_zh: '逻辑之影',
    subtitle: 'Philosophy via Graphic Design',
    subtitle_fa: 'فلسفه از دریچه گرافیک',
    subtitle_fr: 'La philosophie via le design graphique',
    subtitle_de: 'Philosophie durch Grafikdesign',
    subtitle_ru: 'Философия через графический дизайн',
    subtitle_tr: 'Grafik Tasarım Yoluyla Felsefe',
    subtitle_ar: 'الفلسفة عبر التصميم الجرافيكي',
    subtitle_zh: '通过平面设计的哲学',
    description: 'Bridging analytic philosophy and visual systems.',
    description_fa: 'پیوند فلسفه تحلیلی و سیستم‌های بصری.',
    description_fr: 'Combler le fossé entre philosophie analytique et systèmes visuels.',
    description_de: 'Verbindung von analytischer Philosophie und visuellen Systemen.',
    description_ru: 'Связующее звено между аналитической философией и визуальными системами.',
    description_tr: 'Analitik felsefe ile görsel sistemler arasında köprü kurmak.',
    description_ar: 'جسر بين الفلسفة التحليلية والنظم البصرية.',
    description_zh: '连接分析哲学与视觉系统。',
    price: 38.50,
    coverUrl: 'https://picsum.photos/400/600?random=2',
    pages: 215,
    publishDate: '2023-05-20',
  }
];

export const MOCK_JOURNAL: JournalPost[] = [
  {
    id: '1',
    title: 'The Death of the Author in AI Art',
    title_fa: 'مرگ مولف در هنر هوش مصنوعی',
    title_fr: 'La Mort de l\'Auteur dans l\'Art IA',
    title_de: 'Der Tod des Autors in der KI-Kunst',
    title_ru: 'Смерть автора в искусстве ИИ',
    title_tr: 'Yapay Zeka Sanatında Yazarın Ölümü',
    title_ar: 'موت المؤلف في فن الذكاء الاصطناعي',
    title_zh: 'AI艺术中的作者之死',
    excerpt: 'Revisiting Barthes in the era of generative algorithms.',
    excerpt_fa: 'بازخوانی بارت در عصر الگوریتم‌های زایا.',
    excerpt_fr: 'Revisiter Barthes à l\'ère des algorithmes génératifs.',
    excerpt_de: 'Barthes im Zeitalter generativer Algorithmen neu besuchen.',
    excerpt_ru: 'Пересмотр Барта в эпоху генеративных алгоритмов.',
    excerpt_tr: 'Üretken algoritmalar çağında Barthes\'ı yeniden ziyaret etmek.',
    excerpt_ar: 'إعادة النظر في بارت في عصر الخوارزميات التولدية.',
    excerpt_zh: '在生成算法时代重读巴特。',
    content: 'Full content...',
    date: '2024-02-10',
    tags: ['Philosophy', 'AI']
  },
  {
    id: '2',
    title: 'Phenomenology of the Pixel',
    title_fa: 'پدیدارشناسی پیکسل',
    title_fr: 'Phénoménologie du Pixel',
    title_de: 'Phänomenologie des Pixels',
    title_ru: 'Феноменология пикселя',
    title_tr: 'Piksel Fenomenolojisi',
    title_ar: 'ظواهرية البكسل',
    title_zh: '像素的现象学',
    excerpt: 'How resolution alters our perception of reality.',
    excerpt_fa: 'چگونه رزولوشن ادراک ما از واقعیت را تغییر می‌دهد.',
    excerpt_fr: 'Comment la résolution modifie notre perception de la réalité.',
    excerpt_de: 'Wie Auflösung unsere Wahrnehmung der Realität verändert.',
    excerpt_ru: 'Как разрешение меняет наше восприятие реальности.',
    excerpt_tr: 'Çözünürlük gerçeklik algımızı nasıl değiştirir.',
    excerpt_ar: 'كيف تغير الدقة إدراكنا للواقع.',
    excerpt_zh: '分辨率如何改变我们对现实的感知。',
    content: 'Full content...',
    date: '2024-01-15',
    tags: ['Phenomenology', 'Digital Art']
  }
];
